# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Search-LIMITed
version:      1.00
version_from: lib/Class/DBI/Search/LIMITed.pm
installdirs:  site
requires:
    Class::DBI:                    3.0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
